// app.qc - Configuration du projet hello-world
Patente Publique HelloWorld
    Faik'Nom C't'un Tex = "hello-world"
    Faik'Version C't'un Tex = "1.0.0"
    Faik'Auteur C't'un Tex = ""
    Faik'Description C't'un Tex = ""
    Faik'License C't'un Tex = "ISC"
    Faik'Entrée C't'un Tex = "src/index.qc"

    Faik'Dependances C't'un TabloD'Dependance

    Faik'Scripts C't'un TabloD'Script
        Faik'Clean C't'une Fonction
        Piafait
            SupprimeDossier dist
